name: DevOpsAI CI/CD

on:
  push:
    branches:
      - main

jobs:

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: backend
        run: npm test --if-present


  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build


  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    needs:
      - backend
      - frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/devopsai-backend:latest \
            ./backend

      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/devopsai-frontend:latest \
            ./frontend

      - name: Push Backend Image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/devopsai-backend:latest

      - name: Push Frontend Image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/devopsai-frontend:latest


  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /opt/devopsai-platform

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devopsai-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devopsai-frontend:latest

            docker compose down

            docker compose up -d

            docker image prune -f
